// <auto-generated />
using System;
using Infra.Contexto;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Infra.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Dominio.Entidades.Lancamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Credito")
                        .IsRequired()
                        .HasColumnType("varchar(12)");

                    b.Property<DateTime>("Data")
                        .HasColumnType("DATE");

                    b.Property<string>("Debito")
                        .IsRequired()
                        .HasColumnType("varchar(12)");

                    b.Property<int>("IdPlanoDeConta")
                        .HasColumnType("int");

                    b.Property<string>("PlanoDeContaNumeroDaConta")
                        .HasColumnType("varchar(12)");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal");

                    b.HasKey("Id");

                    b.HasIndex("PlanoDeContaNumeroDaConta");

                    b.ToTable("Lancamentos");
                });

            modelBuilder.Entity("Dominio.Entidades.PlanoDeConta", b =>
                {
                    b.Property<string>("NumeroDaConta")
                        .HasColumnType("varchar(12)");

                    b.Property<string>("NomeDaConta")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.HasKey("NumeroDaConta");

                    b.ToTable("PlanoDeContas");
                });

            modelBuilder.Entity("Dominio.Entidades.Lancamento", b =>
                {
                    b.HasOne("Dominio.Entidades.PlanoDeConta", "PlanoDeConta")
                        .WithMany("Lancamentos")
                        .HasForeignKey("PlanoDeContaNumeroDaConta");
                });
#pragma warning restore 612, 618
        }
    }
}
